# Generated by Django 5.0.2 on 2024-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_dp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_points',
            field=models.IntegerField(default=0),
        ),
    ]
