# Generated by Django 5.0.2 on 2024-05-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsWorks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedworks',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
