# Generated by Django 5.0.2 on 2024-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsWorks', '0002_bookedworks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='description',
        ),
        migrations.AddField(
            model_name='works',
            name='slots',
            field=models.IntegerField(default=20),
        ),
    ]
