# Generated by Django 5.0.2 on 2024-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsWorks', '0003_remove_works_description_works_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='booked_slots',
            field=models.IntegerField(default=0),
        ),
    ]
